### ISSUE TITLE
Error run container

### ISSUE THREAD

**Issue by sandie-ai** [HealisticEngineer/Docker#3]
Hello we have a error after build image
![image](https://user-images.githubusercontent.com/62518982/176847868-26b66a38-5db2-4c0f-a1ab-6e60f32e037c.png)

**Comment by HealisticEngineer** [comment]
It seems to be a related issue to the build process, not the container itself.
[https://github.com/MicrosoftDocs/visualstudio-docs/issues/4772](url)

**Comment by sandie-ai** [comment]
Omg sorry, thank you. I have build directly image with powershell and this is good.
It's my first work with a windows container, thank you for your job and your help!

**Comment by HealisticEngineer** [comment]
Good to hear!
