### ISSUE TITLE
ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019

### ISSUE THREAD

**Issue by syedmuzeeb834** [HealisticEngineer/Docker#4]
I am getting below error :: 

C:\ZainTasks\ReportingTools\Docker-PowerBI-master>docker build -t healisticengineer/pbirs1.14 .
[+] Building 1.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019                               1.0s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:d365ab93a48e9b6fcf2d7db6474fbe78c5e725a2768b3ec1388600a078bd3177: not found

**Comment by velbon** [comment]
Please I am having the same error, please can you help:

Build an image from a Dockerfile
(base) gerald@gerald-444 Docker-PowerBI % docker build -t healisticengineer/pbirs1.14 .
[+] Building 1.0s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/serverco  0.9s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore:ltsc2019:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:46b40e526196d42b78d6bc777529203fd51467b095ddcb7acc87fc475c3c5e55: not found
(base) gerald@gerald-444 Docker-PowerBI % docker build -t healisticengineer/pbirs1.0 .
[+] Building 1.0s (3/3) FINISHED

**Comment by HealisticEngineer** [comment]
This is an issue with the docker client, not the image.

Please try some of the resources below for a fix.

https://medium.com/code-kings/docker-how-to-fix-failed-to-solve-with-frontend-dockerfile-v0-error-when-building-a-docker-image-6d7dc95abd27

https://itprohelper.com/docker-failed-to-solve-with-frontend-dockerfile-v0-failed-to-create-llb-definition/

**Comment by arj060892** [comment]
I'm getting following error 

`ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1752732988/Dockerfile: no such file or directory`
